Add coordinate bounds check. Print full-names only when variable or group is not at root level.

diff --git a/diwg_chk b/diwg_chk
--- a/diwg_chk
+++ b/diwg_chk
@@ -437,6 +437,66 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
 	echo "Elapsed time for character-set check = $((date_dff/60))m$((date_dff % 60))s"
     fi # !dbg
     
+    printf "\nTest 4: Check that filename extension matches recommended list ...\n"
+    printf "Recommendation: Files created with the HDF5, HDF-EOS5, or netCDF APIs should have filename extensions \"h5\", \"he5\", or \"nc\", respectively.\n"
+    echo "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182297715"
+    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
+
+    cmd_xtn[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_xtn ${fl_in[${fl_idx}]}"
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	echo ${cmd_xtn[${fl_idx}]}
+    fi # !dbg
+    if [ ${dbg_lvl} -le 1 ]; then
+	if [ -z "${par_opt}" ]; then
+	    eval ${cmd_xtn[${fl_idx}]}
+	    if [ "$?" -ne 0 ]; then
+		printf "Result: FAILURE filename extension failed. Reproduce this single check with:\n${cmd_xtn[${fl_idx}]}\n"
+	    else # !err
+		printf "Result: SUCCESS filename extension check passed.\n"
+	    fi # !err
+	else # !par_opt
+	    eval ${cmd_xtn[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+	    xtn_pid[${fl_idx}]=$!
+	fi # !par_opt
+    fi # !dbg
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	date_crr=$(date +"%s")
+	date_dff=$((date_crr-date_chr))
+	echo "Elapsed time for filename extension check = $((date_dff/60))m$((date_dff % 60))s"
+    fi # !dbg
+    
+    printf "\nTest 5: Check that coordinates have bounds attributes ...\n"
+    printf "Recommendation: Use CF Bounds Attributes\n"
+    echo "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=182296291"
+    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
+
+    cmd_bnd[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_bnd ${fl_in[${fl_idx}]}"
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	echo ${cmd_bnd[${fl_idx}]}
+    fi # !dbg
+    if [ ${dbg_lvl} -le 1 ]; then
+	if [ -z "${par_opt}" ]; then
+	    eval ${cmd_bnd[${fl_idx}]}
+	    if [ "$?" -ne 0 ]; then
+		printf "Result: FAILURE coordinate bounds check failed. Reproduce this single check with:\n${cmd_bnd[${fl_idx}]}\n"
+	    else # !err
+		printf "Result: SUCCESS coordinate bounds check passed.\n"
+	    fi # !err
+	else # !par_opt
+	    eval ${cmd_bnd[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+	    bnd_pid[${fl_idx}]=$!
+	fi # !par_opt
+    fi # !dbg
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	date_crr=$(date +"%s")
+	date_dff=$((date_crr-date_chr))
+	echo "Elapsed time for coordinate bounds check = $((date_dff/60))m$((date_dff % 60))s"
+    fi # !dbg
+    
 done # !fl_idx
 
 date_end=$(date +"%s")
