First version that works. Needs lot of cleanup. Lack parallelism.

diff --git a/diwg_chk b/diwg_chk
--- a/diwg_chk
+++ b/diwg_chk
@@ -240,10 +240,10 @@ else # !drc_in
 fi # !drc_in
 
 # Read files from stdin pipe, positional arguments, or directory glob
-printf "dbg: inp_aut  = ${inp_aut}\n"
-printf "dbg: inp_glb  = ${inp_glb}\n"
-printf "dbg: inp_psn  = ${inp_psn}\n"
-printf "dbg: inp_std  = ${inp_std}\n"
+#printf "dbg: inp_aut  = ${inp_aut}\n"
+#printf "dbg: inp_glb  = ${inp_glb}\n"
+#printf "dbg: inp_psn  = ${inp_psn}\n"
+#printf "dbg: inp_std  = ${inp_std}\n"
 
 # Derived variables
 if [ -n "${drc_out_usr}" ]; then
@@ -336,9 +336,9 @@ fi # !dbg
 # Human-readable summary
 date_srt=$(date +"%s")
 if [ ${dbg_lvl} -ge 0 ]; then
-    printf "diwg_chk, a DIWG Recommendation compliance checker, invoked with command:\n"
+    printf "diwg_chk, a DIWG compliance checker, invoked with command:\n"
     echo "${cmd_ln}"
-    printf "Started DIWG checking at `date`\n"
+    printf "Started DIWG checker at `date`\n"
 fi # !dbg
 
 if [ "${fl_nbr}" -lt 1 ]; then
@@ -355,13 +355,35 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
     #printf "fl_out[${fl_idx}] = ${fl_out[${fl_idx}]}\n"
     
     #if false; then
-    printf "\nChecking file ${fl_idx}...\n"
-    [[ ${dbg_lvl} -ge 0 ]] && date_var=$(date +"%s")
+    printf "\nChecking file #${fl_idx}: ${fl_in[${fl_idx}]}...\n"
     
+    printf "\nTest 1: Check for NaNs ...\n"
+    printf "Recommendation: Earth Science data products should not store NaN in any field values, nor as an indicator of missing or invalid data.\n"
+    printf "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=62818058\n"
+    [[ ${dbg_lvl} -ge 0 ]] && date_nan=$(date +"%s")
+    cmd_nan[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_nan ${fl_in[${fl_idx}]}"
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	echo ${cmd_nan[${fl_idx}]}
+    fi # !dbg
+    if [ ${dbg_lvl} -le 1 ]; then
+	if [ -z "${par_opt}" ]; then
+	    eval ${cmd_nan[${fl_idx}]}
+	    if [ "$?" -ne 0 ]; then
+		printf "${spt_nm}: ERROR NaN check failed. Reproduce check with this:\n${cmd_nan[${fl_idx}]}\n"
+	    else # !err
+		printf "${spt_nm}: SUCCESS NaN check passed.\n"
+	    fi # !err
+	else # !par_opt
+	    eval ${cmd_nan[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+	    nan_pid[${fl_idx}]=$!
+	fi # !par_opt
+    fi # !dbg
+
     if [ ${dbg_lvl} -ge 0 ]; then
 	date_crr=$(date +"%s")
-	date_dff=$((date_crr-date_var))
-	echo "Elapsed time to check foo = $((date_dff/60))m$((date_dff % 60))s"
+	date_dff=$((date_crr-date_nan))
+	echo "Elapsed time to check for NaNs = $((date_dff/60))m$((date_dff % 60))s"
     fi # !dbg
 
     #fi # !false
