Version for 20230517 DIWG meeting

diff --git a/diwg_chk b/diwg_chk
--- a/diwg_chk
+++ b/diwg_chk
@@ -42,14 +42,16 @@ spt_pid=$$ # [nbr] Script PID (process ID)
 # ln -s ~/diwg/diwg_chk ~/sh/diwg_chk
 
 # Debugging and Benchmarking:
-# diwg_chk ~/nco/data/in.nc
-# diwg_chk ~/bm/elmv2_ne30pg2l15.nc
+# diwg_chk ~/nco/data/in.nc ~/nco/data/in_4.nc 
+# diwg_chk ~/data/bm/elmv2_ne30pg2l15.nc
 # diwg_chk ~/data/hdf/MODIS_L2N_20140304T1120.nc > ~/diwg.txt 2>&1 &
+# diwg_chk ~/data/hdf/ > ~/diwg.txt 2>&1 &
+# diwg_chk ~/data/hdf/OMI-Aura_L2-OMAERUV_2013m1004t2338-o49057_v003-2013m1005t053932.nc
 
 # Production usage:
-# diwg_chk --dbg=1 ~/nco/data/in.nc > ~/diwg.txt 2>&1 &
+# diwg_chk --dbg=1 ~/nco/data/in_4.nc > ~/diwg.txt 2>&1 &
 # screen # Start screen
-# diwg_chk --dbg=1 ~/nco/data/in.nc > ~/diwg.txt 2>&1 &
+# diwg_chk --dbg=1 ~/nco/data/in_4.nc > ~/diwg.txt 2>&1 &
 # Ctl-A D # Detach screen
 # tail ~/diwg.txt # Monitor progress
 # screen -ls # List screens
@@ -119,6 +121,10 @@ inp_psn='No' # [sng] Input file list from positional arguments
 inp_std='No' # [sng] Input file list from stdin
 nco_opt='' # [sng] NCO options (e.g., '-6 -t 1')
 vrs_prn='No' # [sng] Print version information
+
+# NCO filters documented in http://nco.sf.net/nco.html#filter
+function ncvarlst { ncks --trd -m ${1} | grep -E ': type' | cut -f 1 -d ' ' | sed 's/://' | sort ; }
+function ncdmnlst { ncks --cdl -m ${1} | cut -d ':' -f 1 | cut -d '=' -s -f 1 ; }
 
 function fnc_usg_prn { # NB: dash supports fnc_nm (){} syntax, not function fnc_nm{} syntax
     # Print usage
@@ -354,10 +360,9 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
     #printf "fl_in[${fl_idx}]  = ${fl_in[${fl_idx}]}\n"
     #printf "fl_out[${fl_idx}] = ${fl_out[${fl_idx}]}\n"
     
-    #if false; then
-    printf "\nChecking file #${fl_idx}: ${fl_in[${fl_idx}]}...\n"
+    printf "\nChecking file #${fl_idx}: ${fl_in[${fl_idx}]} ...\n"
     
-    printf "\nTest 1: Check for NaNs ...\n"
+    printf "\nTest 1: NaN-check ...\n"
     printf "Recommendation: Earth Science data products should not store NaN in any field values, nor as an indicator of missing or invalid data.\n"
     printf "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=62818058\n"
     [[ ${dbg_lvl} -ge 0 ]] && date_nan=$(date +"%s")
@@ -370,9 +375,9 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
 	if [ -z "${par_opt}" ]; then
 	    eval ${cmd_nan[${fl_idx}]}
 	    if [ "$?" -ne 0 ]; then
-		printf "${spt_nm}: ERROR NaN check failed. Reproduce check with this:\n${cmd_nan[${fl_idx}]}\n"
+		printf "Result: FAILURE NaN-check failed. Reproduce check with this:\n${cmd_nan[${fl_idx}]}\n"
 	    else # !err
-		printf "${spt_nm}: SUCCESS NaN check passed.\n"
+		printf "Result: SUCCESS NaN-check passed.\n"
 	    fi # !err
 	else # !par_opt
 	    eval ${cmd_nan[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
@@ -380,19 +385,66 @@ for ((fl_idx=0;fl_idx<fl_nbr;fl_idx++)); do
 	fi # !par_opt
     fi # !dbg
 
-    if [ ${dbg_lvl} -ge 0 ]; then
+    if [ ${dbg_lvl} -ge 1 ]; then
 	date_crr=$(date +"%s")
 	date_dff=$((date_crr-date_nan))
-	echo "Elapsed time to check for NaNs = $((date_dff/60))m$((date_dff % 60))s"
+	echo "Elapsed time for NaN-check = $((date_dff/60))m$((date_dff % 60))s"
     fi # !dbg
 
-    #fi # !false
+    if false; then
+    printf "\nTest 2: Check character set of group, dimension, variable, and attribute names ...\n"
+    printf "Recommendation: Such names shall comply with this regular expression: [A-Za-z][A-Za-z0-9_]*\n"
+    printf "URL: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=78978073\n"
+    [[ ${dbg_lvl} -ge 0 ]] && date_chr=$(date +"%s")
+    var_lst=`ncvarlst ${fl_in[${fl_idx}]}`
+    dmn_lst=`ncdmnlst ${fl_in[${fl_idx}]}`
+#    att_lst=`ncattlst ${fl_in[${fl_idx}]}`
+#    echo "var_lst = ${var_lst}"
+#    echo "dmn_lst = ${dmn_lst}"
+#    if [[ "${var_lst}" =~ ^(.*)([0-9][0-9][0-9][0-9][01][0-9].nc.?)$ ]]; then
+    declare -a var
+    read -r ${var} <<< "${var_lst}"
+    let var_nbr=${#var[@]}
+    echo "var_nbr = ${var_nbr}"
+    echo "var = ${var}"
+
+    if [[ "${var_lst}" =~ [A-Za-z][A-Za-z0-9_]* ]]; then
+	echo "var_lst SUCCESS"
+    else
+	echo "var_lst FAILURE"
+    fi # !var_lst
+
+    cmd_chr[${fl_idx}]="ncks --dbg_lvl=${dbg_lvl} --chk_nan ${fl_in[${fl_idx}]}"
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	echo ${cmd_chr[${fl_idx}]}
+    fi # !dbg
+    if [ ${dbg_lvl} -le 1 ]; then
+	if [ -z "${par_opt}" ]; then
+	    eval ${cmd_chr[${fl_idx}]}
+	    if [ "$?" -ne 0 ]; then
+		printf "Result: FAILURE character-set check failed. Reproduce check with this:\n${cmd_chr[${fl_idx}]}\n"
+	    else # !err
+		printf "Result: SUCCESS character-set check passed.\n"
+	    fi # !err
+	else # !par_opt
+	    eval ${cmd_chr[${fl_idx}]} ${par_opt} # eval always returns 0 on backgrounded processes
+	    nan_pid[${fl_idx}]=$!
+	fi # !par_opt
+    fi # !dbg
+
+    if [ ${dbg_lvl} -ge 1 ]; then
+	date_crr=$(date +"%s")
+	date_dff=$((date_crr-date_chr))
+	echo "Elapsed time for character-set check = $((date_dff/60))m$((date_dff % 60))s"
+    fi # !dbg
+    fi # !false
     
 done # !fl_idx
 
 date_end=$(date +"%s")
-if [ ${dbg_lvl} -ge 0 ]; then
-    printf "Completed DIWG Compliance Checker at `date`\n"
+if [ ${dbg_lvl} -ge 1 ]; then
+    printf "\nCompleted DIWG Compliance Checker at `date`\n"
     date_dff=$((date_end-date_srt))
     echo "Elapsed time $((date_dff/60))m$((date_dff % 60))s"
 fi # !dbg
